# SPDX-FileCopyrightText: 2021 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.customConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "juice-shop.fullname" . }}
  labels:
    {{- include "juice-shop.labels" . | nindent 4 }}
  annotations:
    {{- include "juice-shop.annotations" . | nindent 4 }}
data:
  customConfig.yml: |
    {{ toYaml .Values.customConfig | nindent 4 }}
{{ end }}
