# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: auto-discovery-kubernetes
description: "Automatically creates secureCodeBox Scans for Resources found in the Kubernetes Cluster"

type: application

# version - gets automatically set to the secureCodeBox release version when the helm charts gets published
version: v3.1.0-alpha1
kubeVersion: ">=v1.11.0-0"

keywords:
  - security
  - secureCodeBox
  - auto-discovery
home: https://www.securecodebox.io/docs/getting-started/installation
icon: https://www.securecodebox.io/img/Icon_Blue.svg
sources:
  - https://github.com/secureCodeBox/secureCodeBox
maintainers:
  - name: iteratec GmbH
    email: secureCodeBox@iteratec.com

# Artifacthub.io specific annotations
# https://artifacthub.io/docs/topics/annotations/helm/
annotations:
  artifacthub.io/changes: |
    - first initial introduction of the new secureCodeBox Autodiscovery
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/images: |
    - name: securecodebox-auto-discovery-kubernetes
      image: docker.io/securecodebox/auto-discovery-kubernetes
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://www.securecodebox.io/docs/getting-started/installation
    - name: Homepage
      url: https://www.securecodebox.io
    - name: iteratec GmbH
      url: https://www.iteratec.com
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Seamless Upgrades
  artifacthub.io/prerelease: "true"
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/securecodebox/operator
