# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

# permissions for end users to view parsedefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parsedefinition-viewer-role
rules:
  - apiGroups:
      - execution.securecodebox.io
    resources:
      - parsedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - execution.securecodebox.io
    resources:
      - parsedefinitions/status
    verbs:
      - get
