# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

# permissions for end users to edit parsedefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parsedefinition-editor-role
rules:
  - apiGroups:
      - execution.securecodebox.io
    resources:
      - parsedefinitions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - execution.securecodebox.io
    resources:
      - parsedefinitions/status
    verbs:
      - get
