# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

# permissions for end users to edit scancompletionhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scancompletionhook-editor-role
rules:
- apiGroups:
  - execution.securecodebox.io
  resources:
  - scancompletionhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - execution.securecodebox.io
  resources:
  - scancompletionhooks/status
  verbs:
  - get
