# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

# permissions for end users to edit scans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scan-editor-role
rules:
  - apiGroups:
      - execution.securecodebox.io
    resources:
      - scans
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - execution.securecodebox.io
    resources:
      - scans/status
    verbs:
      - get
