# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

version: "3.8"
services:
  bodgeit:
    image: psiinon/bodgeit:latest
    ports:
      - 8080:8080
# Website will be available under http://localhost:8080/bodgeit
