# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: execution.securecodebox.io/v1
kind: ScanCompletionHook
metadata:
  name: "echo-r"
spec:
  image: "echo"
  type: "ReadOnly"
  env: []
