# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: execution.securecodebox.io/v1
kind: ScheduledScan
metadata:
  name: scheduled-nmap-localhost
spec:
  interval: 1m
  successfulJobsHistoryLimit: 2
  scanSpec:
    scanType: "nmap"
    parameters:
      - "-Pn"
      - "192.168.178.24"
