# Default values for imperative-subsequent-scans Hook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cascade:
  # cascade.amassNmap -- True if you want to cascade nmap scans for each subdomain found by amass, otherwise false.
  amassNmap: false
  # cascade.nmapSmb -- True if you want to cascade nmap SMB scans for each SMB Port found by nmap, otherwise false.
  nmapSmb: false
  # cascade.nmapSsh -- True if you want to cascade SSH scans for each SSH Port found by nmap, otherwise false.
  nmapSsh: false
  # cascade.nmapSsl -- True if you want to cascade SSL scans for each HTTP Port found by nmap, otherwise false.
  nmapSsl: false
  # cascade.nmapNikto -- True if you want to cascade Nikto scans for each HTTP Port found by nmap, otherwise false.
  nmapNikto: false
  # cascade.nmapZapBaseline -- True if you want to cascade ZAP scans for each HTTP Port found by nmap, otherwise false.
  nmapZapBaseline: false

image:
  # image.tag - defaults to the charts version
  # image.repository -- Hook image repository
  repository: docker.io/securecodebox/hook-imperative-subsequent-scans
  # parserImage.tag -- Parser image tag
  # @default -- defaults to the charts version
  tag: null
