apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auto-discovery-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: auto-discovery-leader-election-role
subjects:
- kind: ServiceAccount
  name: auto-discovery
  namespace: {{ .Release.Namespace }}
